name = "meebot-io"
pages_build_output_dir = "public"
compatibility_date = "2025-03-06"
compatibility_flags = ["nodejs_compat"]

[vars]
CHAIN_ID = "13390"
DRPC_RPC_URL = "http://rpc.meechain.run.place"
VITE_RPC_URL = "https://ritual-chain--pouaun2499.replit.app"
VITE_TOKEN_CONTRACT_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
VITE_NFT_CONTRACT_ADDRESS = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
VITE_STAKING_CONTRACT_ADDRESS = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
